version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/jar-elhub.jar
  discard-paths: yes