version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package package -X
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/jar-elhub.jar
  discard-paths: yes